"use client";

import { useState, useRef } from "react";
import { Download, FileText, X, Printer, Copy, CheckCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { TripLocation, RouteInfo } from "@/types/trip";
import { getDayColor } from "./TripStopsList";

interface ExportItineraryProps {
  locations: TripLocation[];
  routes: RouteInfo[];
  days: number[];
  isOpen: boolean;
  onClose: () => void;
}

function formatDuration(seconds: number): string {
  const mins = Math.round(seconds / 60);
  if (mins < 60) return `${mins} min`;
  const hours = Math.floor(mins / 60);
  const remainingMins = mins % 60;
  return remainingMins > 0 ? `${hours}h ${remainingMins}m` : `${hours}h`;
}

function formatDistance(meters: number): string {
  if (meters < 1000) return `${Math.round(meters)} m`;
  return `${(meters / 1000).toFixed(1)} km`;
}

export function ExportItinerary({ 
  locations, 
  routes, 
  days, 
  isOpen, 
  onClose,
}: ExportItineraryProps) {
  const [copied, setCopied] = useState(false);
  const [exporting, setExporting] = useState(false);
  const printRef = useRef<HTMLDivElement>(null);

  if (!isOpen) return null;

  // Group locations by day
  const locationsByDay = days.reduce((acc, day) => {
    acc[day] = locations.filter(l => (l.day || 1) === day);
    return acc;
  }, {} as Record<number, TripLocation[]>);

  // Calculate total stats
  const totalDistance = routes.reduce((sum, r) => sum + r.distance, 0);
  const totalDuration = routes.reduce((sum, r) => sum + r.duration, 0);

  // Get route info for a location (route TO the next location)
  const getRouteAfter = (locationId: string) => {
    const index = locations.findIndex(l => l.id === locationId);
    if (index >= 0 && index < routes.length) {
      return routes[index];
    }
    return null;
  };

  // Generate text content for export
  const generateTextContent = () => {
    let content = "═══════════════════════════════════════\n";
    content += "        VOYAGE AI TRIP ITINERARY\n";
    content += "═══════════════════════════════════════\n\n";
    content += `📊 Trip Summary\n`;
    content += `   Total Distance: ${formatDistance(totalDistance)}\n`;
    content += `   Total Duration: ${formatDuration(totalDuration)}\n`;
    content += `   Total Stops: ${locations.length}\n`;
    content += `   Days: ${days.length}\n\n`;

    days.forEach(day => {
      const dayLocations = locationsByDay[day] || [];
      const dayDistance = dayLocations.reduce((sum, loc) => {
        const route = getRouteAfter(loc.id);
        return sum + (route?.distance || 0);
      }, 0);
      const dayDuration = dayLocations.reduce((sum, loc) => {
        const route = getRouteAfter(loc.id);
        return sum + (route?.duration || 0);
      }, 0);

      content += `───────────────────────────────────────\n`;
      content += `📅 DAY ${day}\n`;
      content += `   Distance: ${formatDistance(dayDistance)} | Duration: ${formatDuration(dayDuration)}\n`;
      content += `───────────────────────────────────────\n\n`;

      dayLocations.forEach((location, index) => {
        const globalIndex = locations.findIndex(l => l.id === location.id) + 1;
        const route = getRouteAfter(location.id);
        const isLast = index === dayLocations.length - 1;

        content += `   ${globalIndex}. ${location.name.split(",")[0]}\n`;
        if (location.description) {
          content += `      ${location.description}\n`;
        }
        if (location.address) {
          content += `      📍 ${location.address}\n`;
        }
        content += `      Type: ${location.type || "Location"}\n`;
        content += `      Coordinates: ${location.coordinates.lat.toFixed(4)}, ${location.coordinates.lng.toFixed(4)}\n`;

        if (route && !isLast) {
          content += `\n      ↓ ${formatDistance(route.distance)} (${formatDuration(route.duration)})\n\n`;
        } else {
          content += "\n";
        }
      });

      content += "\n";
    });

    content += "═══════════════════════════════════════\n";
    content += "  Generated by Voyage AI Trip Planner\n";
    content += "═══════════════════════════════════════\n";

    return content;
  };

  // Generate HTML content for printing
  const generateHTMLContent = () => {
    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Trip Itinerary - Voyage AI</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 20px; color: #333; }
    .header { text-align: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 2px solid #6366f1; }
    .header h1 { color: #6366f1; font-size: 28px; margin-bottom: 5px; }
    .header p { color: #666; }
    .summary { display: flex; justify-content: center; gap: 30px; margin-bottom: 30px; padding: 15px; background: #f8f9fa; border-radius: 10px; }
    .summary-item { text-align: center; }
    .summary-item .value { font-size: 24px; font-weight: bold; color: #6366f1; }
    .summary-item .label { font-size: 12px; color: #666; }
    .day { margin-bottom: 30px; page-break-inside: avoid; }
    .day-header { padding: 10px 15px; border-radius: 8px; margin-bottom: 15px; color: white; display: flex; justify-content: space-between; align-items: center; }
    .day-header h2 { font-size: 18px; }
    .day-header .stats { font-size: 12px; opacity: 0.9; }
    .location { padding: 15px; border-left: 3px solid #ddd; margin-left: 20px; margin-bottom: 10px; }
    .location-header { display: flex; align-items: center; gap: 10px; margin-bottom: 5px; }
    .location-number { width: 28px; height: 28px; border-radius: 50%; color: white; display: flex; align-items: center; justify-content: center; font-weight: bold; font-size: 14px; }
    .location-name { font-weight: 600; font-size: 16px; }
    .location-type { font-size: 11px; padding: 2px 8px; border-radius: 10px; background: #f0f0f0; color: #666; }
    .location-desc { color: #666; font-size: 13px; margin: 5px 0 5px 38px; }
    .location-address { color: #8b5cf6; font-size: 12px; margin-left: 38px; }
    .route-info { margin: 10px 0 10px 38px; padding: 8px 12px; background: #f8f9fa; border-radius: 6px; font-size: 12px; color: #666; display: inline-block; }
    .route-info strong { color: #333; }
    .footer { text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; color: #999; font-size: 12px; }
    @media print { body { padding: 0; } .day { page-break-inside: avoid; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>✈️ Trip Itinerary</h1>
    <p>Generated by Voyage AI Trip Planner</p>
  </div>

  <div class="summary">
    <div class="summary-item">
      <div class="value">${formatDistance(totalDistance)}</div>
      <div class="label">Total Distance</div>
    </div>
    <div class="summary-item">
      <div class="value">${formatDuration(totalDuration)}</div>
      <div class="label">Total Duration</div>
    </div>
    <div class="summary-item">
      <div class="value">${locations.length}</div>
      <div class="label">Stops</div>
    </div>
    <div class="summary-item">
      <div class="value">${days.length}</div>
      <div class="label">Days</div>
    </div>
  </div>

  ${days.map(day => {
    const dayLocations = locationsByDay[day] || [];
    const dayColor = getDayColor(day).bg;
    const dayDistance = dayLocations.reduce((sum, loc) => {
      const route = getRouteAfter(loc.id);
      return sum + (route?.distance || 0);
    }, 0);
    const dayDuration = dayLocations.reduce((sum, loc) => {
      const route = getRouteAfter(loc.id);
      return sum + (route?.duration || 0);
    }, 0);

    return `
    <div class="day">
      <div class="day-header" style="background: ${dayColor}">
        <h2>📅 Day ${day}</h2>
        <div class="stats">${formatDistance(dayDistance)} • ${formatDuration(dayDuration)}</div>
      </div>
      ${dayLocations.map((location, index) => {
        const globalIndex = locations.findIndex(l => l.id === location.id) + 1;
        const route = getRouteAfter(location.id);
        const isLast = index === dayLocations.length - 1;

        return `
        <div class="location" style="border-left-color: ${dayColor}">
          <div class="location-header">
            <div class="location-number" style="background: ${dayColor}">${globalIndex}</div>
            <span class="location-name">${location.name.split(",")[0]}</span>
            <span class="location-type">${location.type || "Location"}</span>
          </div>
          ${location.description ? `<div class="location-desc">${location.description}</div>` : ""}
          ${location.address ? `<div class="location-address">📍 ${location.address}</div>` : ""}
          ${route && !isLast ? `
            <div class="route-info">
              ↓ <strong>${formatDistance(route.distance)}</strong> (${formatDuration(route.duration)})
            </div>
          ` : ""}
        </div>
        `;
      }).join("")}
    </div>
    `;
  }).join("")}

  <div class="footer">
    Generated on ${new Date().toLocaleDateString()} by Voyage AI Trip Planner
  </div>
</body>
</html>
    `;
  };

  // Copy to clipboard
  const handleCopyText = async () => {
    const content = generateTextContent();
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Download as text file
  const handleDownloadText = () => {
    const content = generateTextContent();
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `trip-itinerary-${new Date().toISOString().split("T")[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Open print preview with HTML
  const handlePrint = () => {
    const htmlContent = generateHTMLContent();
    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(htmlContent);
      printWindow.document.close();
      setTimeout(() => {
        printWindow.print();
      }, 250);
    }
  };

  // Download as HTML file
  const handleDownloadHTML = () => {
    const htmlContent = generateHTMLContent();
    const blob = new Blob([htmlContent], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `trip-itinerary-${new Date().toISOString().split("T")[0]}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />
      
      {/* Modal */}
      <div className="relative bg-background border border-border rounded-2xl shadow-2xl w-full max-w-md mx-4 overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-border/50">
          <div className="flex items-center gap-3">
            <div className="size-10 rounded-xl bg-gradient-to-br from-green-600 to-emerald-600 flex items-center justify-center">
              <Download className="size-5 text-white" />
            </div>
            <div>
              <h2 className="font-semibold">Export Itinerary</h2>
              <p className="text-xs text-muted-foreground">Download your trip plan</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-lg hover:bg-accent transition-colors"
          >
            <X className="size-5" />
          </button>
        </div>

        {/* Summary */}
        <div className="p-4 bg-accent/30">
          <div className="grid grid-cols-4 gap-2 text-center">
            <div>
              <div className="text-lg font-bold text-primary">{days.length}</div>
              <div className="text-[10px] text-muted-foreground">Days</div>
            </div>
            <div>
              <div className="text-lg font-bold text-primary">{locations.length}</div>
              <div className="text-[10px] text-muted-foreground">Stops</div>
            </div>
            <div>
              <div className="text-lg font-bold text-primary">{formatDistance(totalDistance)}</div>
              <div className="text-[10px] text-muted-foreground">Distance</div>
            </div>
            <div>
              <div className="text-lg font-bold text-primary">{formatDuration(totalDuration)}</div>
              <div className="text-[10px] text-muted-foreground">Duration</div>
            </div>
          </div>
        </div>

        {/* Export Options */}
        <div className="p-4 space-y-2">
          <p className="text-xs text-muted-foreground mb-3">Choose export format:</p>
          
          {/* Print / PDF */}
          <button
            onClick={handlePrint}
            className="w-full flex items-center gap-3 p-3 rounded-lg border border-border/50 hover:bg-accent/50 transition-colors text-left"
          >
            <div className="size-10 rounded-lg bg-red-500/10 flex items-center justify-center">
              <Printer className="size-5 text-red-500" />
            </div>
            <div className="flex-1">
              <div className="font-medium text-sm">Print / Save as PDF</div>
              <div className="text-xs text-muted-foreground">Beautiful formatted itinerary with day colors</div>
            </div>
          </button>

          {/* Download HTML */}
          <button
            onClick={handleDownloadHTML}
            className="w-full flex items-center gap-3 p-3 rounded-lg border border-border/50 hover:bg-accent/50 transition-colors text-left"
          >
            <div className="size-10 rounded-lg bg-blue-500/10 flex items-center justify-center">
              <FileText className="size-5 text-blue-500" />
            </div>
            <div className="flex-1">
              <div className="font-medium text-sm">Download HTML</div>
              <div className="text-xs text-muted-foreground">Open in browser, can print to PDF</div>
            </div>
          </button>

          {/* Download Text */}
          <button
            onClick={handleDownloadText}
            className="w-full flex items-center gap-3 p-3 rounded-lg border border-border/50 hover:bg-accent/50 transition-colors text-left"
          >
            <div className="size-10 rounded-lg bg-gray-500/10 flex items-center justify-center">
              <FileText className="size-5 text-gray-500" />
            </div>
            <div className="flex-1">
              <div className="font-medium text-sm">Download Text</div>
              <div className="text-xs text-muted-foreground">Plain text format, easy to share</div>
            </div>
          </button>

          {/* Copy to Clipboard */}
          <button
            onClick={handleCopyText}
            className="w-full flex items-center gap-3 p-3 rounded-lg border border-border/50 hover:bg-accent/50 transition-colors text-left"
          >
            <div className="size-10 rounded-lg bg-violet-500/10 flex items-center justify-center">
              {copied ? (
                <CheckCircle className="size-5 text-green-500" />
              ) : (
                <Copy className="size-5 text-violet-500" />
              )}
            </div>
            <div className="flex-1">
              <div className="font-medium text-sm">
                {copied ? "Copied!" : "Copy to Clipboard"}
              </div>
              <div className="text-xs text-muted-foreground">Paste into any app or document</div>
            </div>
          </button>
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-border/50 bg-accent/20">
          <Button variant="outline" onClick={onClose} className="w-full">
            Close
          </Button>
        </div>
      </div>
    </div>
  );
}
